<?php $banners = $this->getBannersCollection(); ?>
<div class="banners">
    <?php foreach($banners as $banner): ?>
    <div class="banner">
        <a href="<?php echo $banner->getUrl(); ?>">
            <h1 class="title"><?php echo $banner->getTitle(); ?></h1>
            <div class="image" style="background-image: url('<?php echo $banner->getImagePath(); ?>');" alt=""></div>
        </a>
    </div>
    <?php endforeach; ?>
</div>