<?php $banners = $this->getBannersCollection(); ?>
<div class="banners">
    <?php foreach($banners as $banner): ?>
    <div class="banner">
        <a href="<?php echo $this->escapeHtml($banner->getUrl()); ?>">
            <h1 class="title"><?php echo $this->escapeHtml($banner->getTitle()); ?></h1>
            <div class="image" style="background-image: url('/media<?php echo $this->escapeHtml($banner->getImagePath()); ?>');" alt=""></div>
        </a>
    </div>
    <?php endforeach; ?>
</div>